### ISSUE TITLE
(ENH) Any thoughts of packaging this in a docker container?

### ISSUE THREAD

**Issue by bthome** [adpeace/zwave-mqtt-bridge#2]
Looking for a reliable zwave-mqtt-bridge (several out there so test driving), would like to see your work published into a docker container to simplify install and future updates.

Thanks for your work.

**Comment by think-free** [comment]
Just did it for my home automation software :
https://github.com/think-free/Docker/tree/master/zwave-mqtt-bridge

**Comment by adpeace** [comment]
Nice, thank you.  BTW I made this Python 3 compatible in the latest commit so if you preferred you could switch your container to Python 3.  I will close out this issue.
